version: '3'

services:
  app:
    image: 61955aa903de  # <-- image from v3.1
    # docker build 的設定
    build:
      context: .
    #port 對應
    ports:
      - "8701:8701"
    #volumes 對應
    volumes:
      - ./app:/app
    #指令
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8701"