# Generated by Django 4.0.6 on 2022-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('user_phone', models.IntegerField(null=True)),
                ('user_email', models.EmailField(max_length=30, null=True)),
            ],
        ),
    ]
