# Generated by Django 4.0.6 on 2022-08-02 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.TextField(default=' ')),
                ('user_nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='added_device_list',
            fields=[
                ('added_device_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='alive_verification_code',
            fields=[
                ('alive_verification_code_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('verification_code', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category_detail',
            fields=[
                ('category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='home_list',
            fields=[
                ('home_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('home_address', models.CharField(default=' ', max_length=30)),
                ('home_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_belong_home',
            fields=[
                ('user_belong_home', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_user', to='api.home_list')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_home', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='device_type',
            fields=[
                ('device_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(max_length=30)),
                ('device_type_description', models.CharField(blank=True, max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category_detail')),
            ],
        ),
        migrations.CreateModel(
            name='device_data',
            fields=[
                ('device_data_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data_value', models.CharField(max_length=30)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.added_device_list')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_type')),
            ],
        ),
        migrations.AddField(
            model_name='added_device_list',
            name='device_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_type'),
        ),
        migrations.AddField(
            model_name='added_device_list',
            name='home_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home_list'),
        ),
    ]
