# Generated by Django 4.1 on 2022-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="chat_room_data",
            fields=[
                (
                    "message_id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("chat_room_name", models.CharField(max_length=30)),
                ("message", models.TextField()),
            ],
        ),
    ]
