# Generated by Django 4.0.6 on 2022-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode_key_data',
            name='fan_level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mode_key_data',
            name='fan_switch',
            field=models.BooleanField(default=False),
        ),
    ]
