# Generated by Django 4.1 on 2022-09-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device_data",
            name="data_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
