# Generated by Django 4.1 on 2022-09-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device_data",
            old_name="data",
            new_name="data_status",
        ),
    ]
