# Generated by Django 4.0.6 on 2022-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_password',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
