# Generated by Django 4.1 on 2022-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home_admin",
            old_name="home_id",
            new_name="home",
        ),
        migrations.AlterField(
            model_name="home_admin",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
