# Generated by Django 5.0.7 on 2024-07-24 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_device_data_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_data',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device_list',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
