# Generated by Django 4.0.6 on 2022-07-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_info_user_name_info_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_belong_home',
            fields=[
                ('user_belong_home', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('home_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
