# Generated by Django 4.0.6 on 2022-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_room_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_room',
            fields=[
                ('chat_room_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('message', models.ManyToManyField(related_name='chat_room_message', to='api.chat_room_data')),
            ],
        ),
    ]
