# Generated by Django 4.1 on 2022-08-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_home_id_home_admin_home_alter_home_admin_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home_list",
            old_name="homeUser",
            new_name="user",
        ),
    ]
