# Generated by Django 4.1 on 2022-08-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home_list",
            old_name="home_address",
            new_name="home_name",
        ),
    ]
