# Generated by Django 4.0.6 on 2022-07-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_belong_home_alter_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_belong_home',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user_info'),
        ),
    ]
