# Generated by Django 4.0.6 on 2022-08-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_homeuser_home_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='mode_key_data',
            fields=[
                ('mode_key_data_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tplink_switch_mode_key', models.CharField(max_length=6)),
                ('mode_key_time', models.DateTimeField(auto_now_add=True)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home_list')),
            ],
        ),
    ]
