# Generated by Django 4.0.6 on 2022-07-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_belong_home_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_belong_home',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_home', to='api.user_info'),
        ),
        migrations.CreateModel(
            name='home_list',
            fields=[
                ('home_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('home_address', models.CharField(default=' ', max_length=30)),
                ('home_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_info')),
            ],
        ),
    ]
