# Generated by Django 4.0.6 on 2022-07-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_belong_home_user_id_home_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_belong_home',
            name='home_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_user', to='api.home_list'),
        ),
    ]
