# Generated by Django 4.0.6 on 2022-07-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_belong_home_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_list',
            old_name='home_owner_id',
            new_name='home_owner',
        ),
    ]
