# Generated by Django 4.0.6 on 2022-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_home_owner_id_home_list_home_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_list',
            name='home_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_belong_home',
            name='user_belong_home',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
