# Generated by Django 4.0.6 on 2022-07-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_home_list_home_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='added_device_list',
            fields=[
                ('added_device_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home_list')),
            ],
        ),
    ]
