# Generated by Django 4.0.6 on 2022-07-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_added_device_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_type',
            fields=[
                ('device_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(max_length=30)),
                ('device_type_description', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='added_device_list',
            name='device_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.device_type'),
            preserve_default=False,
        ),
    ]
