# Generated by Django 4.0.6 on 2022-07-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_device_type_added_device_list_device_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='alive_verification_code',
            fields=[
                ('alive_verification_code_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('verification_code', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
