# Generated by Django 4.0.6 on 2022-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alive_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_detail',
            fields=[
                ('category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
