# Generated by Django 4.0.6 on 2022-07-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_data',
            fields=[
                ('device_data_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data_value', models.CharField(max_length=30)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_type')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.added_device_list')),
            ],
        ),
    ]
