# Generated by Django 4.0.6 on 2022-07-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_device_type_category_device_data'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='device_type',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category_detail'),
            preserve_default=False,
        ),
    ]
