# Generated by Django 4.0.6 on 2022-07-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_device_type_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_type',
            name='category_id',
        ),
    ]
