# Generated by Django 4.0.6 on 2022-07-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_device_type_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_data',
            old_name='data_type',
            new_name='device_type',
        ),
    ]
