# Generated by Django 4.0.6 on 2022-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_data_type_device_data_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
