# Generated by Django 4.0.6 on 2022-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_info_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_password',
            field=models.TextField(default=' '),
        ),
    ]
