# Generated by Django 4.0.6 on 2022-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_info_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_password',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
