# Generated by Django 4.0.6 on 2022-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_user_info_user_email_alter_user_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_password',
            field=models.TimeField(default=' '),
        ),
    ]
